export const quizActions = {
  CREATE_NEW_QUIZ_INITIATE: "CREATE_NEW_QUIZ_INITIATE",
  CREATE_NEW_QUIZ_SUCCESS: "CREATE_NEW_QUIZ_SUCCESS",
  CREATE_NEW_QUIZ_FAILURE: "CREATE_NEW_QUIZ_FAILURE",
  GET_QUIZ_DATA_INITIATE:"GET_QUIZ_DATA_INITIATE",
  GET_QUIZ_DATA_SUCCESS:"GET_QUIZ_DATA_SUCCESS",
  GET_QUIZ_DATA_FAILURE:"GET_QUIZ_DATA_FAILURE",
  SUBMIT_QUIZ_INITIATE: "SUBMIT_QUIZ_INITIATE",
  SUBMIT_QUIZ_SUCCESS: "SUBMIT_QUIZ_SUCCESS",
  SUBMIT_QUIZ_FAILURE: "SUBMIT_QUIZ_FAILURE",
}